---
#- debug:
#    msg: "{{ chrony_os_settings }}"

- name: ensure chrony dependncy packages are installed
  action: "{{ chrony_os_settings.pkg_mgr }}"
  args: chrony_os_settings.pkg_mgr_args
  with_items: chrony_os_settings.pre_pkgs
  when: chrony_os_settings.pre_pkgs|length > 0

- name: ensure chrony packages are installed
  action: "{{ chrony_os_settings.pkg_mgr }}"
  args: chrony_os_settings.pkg_mgr_args
  with_items: chrony_os_settings.pkgs
  when: chrony_os_settings.pkgs|length > 0

- name: update chrony.conf from template
  template:
    src: chrony.conf
    dest: "{{ chrony_conf_path }}"
    owner: root
    group: root
    mode: 0644
  register: chrony_conf

- name: ensure chrony service is started and enabled
  service: 
    name: chrony
    enabled: yes
    state: started 
    pattern: chronyd

- name: ensure chrony service is restarted if necessary
  service: 
    name: chrony
    state: restarted 
    pattern: chronyd
  when: chrony_conf|changed
